app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# Al definir las rutas en los controladores estas rutas son innecesarias, no utilizar
area_index:
    path:      /areafootball/
    defaults:  { _controller: AppBundle:AreaFootball\AreaFootball:index}
fixtures_index:
    path:      /areafootball/fixtures
    defaults:  { _controller: AppBundle:AreaFootball\Fixtures:index}
match_index:
    path:      /areafootball/match
    defaults:  { _controller: AppBundle:AreaFootball\Match:index}
match_read:
    path:      /areafootball/match/{id_match}
    defaults:  { _controller: AppBundle:AreaFootball\Match:read}
simulatews_index:
    path:      /areafootball/simulatews/{page}
    defaults:  { _controller: AppBundle:AreaFootball\SimulateWS\SimulateWS:index, page: 1 }
    requirements:
       page: '\d+'